language: "zh-CN"

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  path_filters:
    - "!*.lock"
    - "!pubspec.lock"
    - "!build/**"
    - "!.dart_tool/**"
    - "!ios/Pods/**"
    - "!ios/Runner.xcodeproj/**"
    - "!ios/Runner.xcworkspace/**"
    - "!macos/Podfile.lock"
    - "!macos/Runner.xcodeproj/**"
    - "!macos/Runner.xcworkspace/**"
    - "!assets/**"
    - "!patch/**"
    - "!debian/**"

chat:
  auto_reply: true
