import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:syntax_highlight/syntax_highlight.dart';
import 'package:venera_nas/foundation/app_theme.dart';
import 'package:venera_nas/foundation/app.dart';
import 'package:venera_nas/foundation/app_page_route.dart';
import 'package:venera_nas/foundation/appdata.dart';
import 'package:venera_nas/foundation/comic_source/comic_source.dart';
import 'package:venera_nas/foundation/comic_type.dart';
import 'package:venera_nas/foundation/consts.dart';
import 'package:venera_nas/foundation/favorites.dart';
import 'package:venera_nas/foundation/history.dart';
import 'package:venera_nas/foundation/image_provider/cached_image.dart';
import 'package:venera_nas/foundation/image_provider/history_image_provider.dart';
import 'package:venera_nas/foundation/image_provider/local_comic_image.dart';
import 'package:venera_nas/foundation/local.dart';
import 'package:venera_nas/foundation/read_later.dart';
import 'package:venera_nas/foundation/log.dart';
import 'package:venera_nas/foundation/res.dart';
import 'package:venera_nas/network/cloudflare.dart';
import 'package:venera_nas/pages/comic_details_page/comic_page.dart';
import 'package:venera_nas/pages/favorites/favorites_page.dart';
import 'package:venera_nas/utils/ext.dart';
import 'package:venera_nas/utils/io.dart';
import 'package:venera_nas/utils/tags_translation.dart';
import 'package:venera_nas/utils/translations.dart';
import 'package:window_manager/window_manager.dart';

part 'image.dart';
part 'appbar.dart';
part 'button.dart';
part 'consts.dart';
part 'flyout.dart';
part 'layout.dart';
part 'loading.dart';
part 'menu.dart';
part 'message.dart';
part 'navigation_bar.dart';
part 'pop_up_widget.dart';
part 'scroll.dart';
part 'select.dart';
part 'side_bar.dart';
part 'comic.dart';
part 'effects.dart';
part 'gesture.dart';
part 'code.dart';
part 'home_section_card.dart';


